extends Node2D
# Main game scene — spawns multiple enemy types in escalating waves,
# drops stacking weapon upgrades, tracks score and stats.
# Endless scrolling world generated by WFC. Camera follows player.
# Enemies spawn around the player's current position, off-screen.

const SPAWN_DISTANCE := 400.0   # spawn this far from player
const MIN_SPAWN_INTERVAL := 0.30
const BASE_SPAWN_INTERVAL := 1.0
const UPGRADE_DROP_CHANCE := 0.3

var enemy_scenes := {
	"squirrel": preload("res://scenes/enemies/squirrel.tscn"),
	"rat":      preload("res://scenes/enemies/rat.tscn"),
	"mole":     preload("res://scenes/enemies/mole.tscn"),
	"raccoon":  preload("res://scenes/enemies/raccoon.tscn"),
}

var pickup_scene: PackedScene = preload("res://scenes/pickup/pickup.tscn")
var powerup_scene: PackedScene = preload("res://scenes/pickup/powerup.tscn")
var treasure_scene: PackedScene = preload("res://scenes/pickup/treasure.tscn")
var boss_scene: PackedScene = preload("res://scenes/enemies/boss.tscn")
var donald_boss_scene: PackedScene = preload("res://scenes/enemies/donald_boss.tscn")

var score: int = 0
var gold: int = 0
var game_over := false
var elapsed_time := 0.0
var enemies_killed := 0
# Boss wave state
var _boss_wave := 0             # current wave number (0 = not yet triggered)
var _boss_wave_active := false  # bosses currently alive
var _bosses_alive := 0          # how many bosses remain in current waveaw
var _boss_fight_start := 0.0    # elapsed_time when wave started
var _boss_fight_duration := 0.0 # how long last wave took to clear
var _boss_respawn_timer := 0.0  # countdown to next wave
var _boss_triggered := false    # initial trigger (2+ weapons at level 3)
# Power-up spawn timer
var _powerup_timer := 0.0
const POWERUP_INTERVAL := 12.0   # seconds between random powerup spawns
const POWERUP_SPAWN_RADIUS := 300.0
const THUNDER_RADIUS := 200.0    # lightning AoE range
const THUNDER_DAMAGE := 3        # damage per enemy hit
const FREEZE_DURATION := 3.0     # ice scroll freeze time

var powerup_types := [
	"life_pot", "scroll_fire", "scroll_ice", "scroll_thunder",
	"gem_red", "gem_green", "gem_purple", "nut",
]

# Spawn weights: [current_weight, seconds_until_unlocked]
var enemy_weights := {
	"squirrel": [10, 0.0],
	"rat":      [0,  5.0],
	"mole":     [0,  20.0],
	"raccoon":  [0,  35.0],
}

var upgrade_types := ["spread", "rapid", "pierce", "bigshot", "homing", "orbit", "rear"]

@onready var player: CharacterBody2D = $Player
@onready var spawn_timer: Timer = $SpawnTimer
@onready var hud: CanvasLayer = $HUD
@onready var world_gen: Node2D = $WorldGenerator


func _ready() -> void:
	Stats.reset()
	player.died.connect(_on_player_died)
	player.health_changed.connect(_on_player_health_changed)
	player.mods_changed.connect(_on_mods_changed)
	player.buff_changed.connect(hud.on_buff_changed)
	spawn_timer.wait_time = BASE_SPAWN_INTERVAL
	spawn_timer.timeout.connect(_on_spawn_timer_timeout)
	hud.update_health(player.health)
	hud.update_mods(player.mods)

	# Initialize the WFC world around the player
	world_gen.init_world(player)

	# MK64 countdown then start music
	SoundManager.play_countdown()
	SoundManager.play_music()


func _process(delta: float) -> void:
	if game_over and Input.is_action_just_pressed("restart"):
		get_tree().reload_current_scene()
		return

	if game_over:
		return

	elapsed_time += delta
	_update_enemy_weights()
	_update_boss_respawn(delta)
	_update_powerup_spawn(delta)

	# Continuously reduce spawn interval
	var new_interval := BASE_SPAWN_INTERVAL - (elapsed_time * 0.012)
	spawn_timer.wait_time = maxf(new_interval, MIN_SPAWN_INTERVAL)


# ── Enemy weight ramping ─────────────────────────────────────────────────

func _update_enemy_weights() -> void:
	for enemy_name: String in enemy_weights:
		var data: Array = enemy_weights[enemy_name]
		var min_time: float = data[1]
		if elapsed_time >= min_time:
			match enemy_name:
				"squirrel":
					data[0] = 10
				"rat":
					data[0] = mini(int((elapsed_time - min_time) * 0.5), 10)
				"mole":
					data[0] = mini(int((elapsed_time - min_time) * 0.2), 5)
				"raccoon":
					data[0] = mini(int((elapsed_time - min_time) * 0.15), 5)


func _pick_enemy_type() -> String:
	var total_weight := 0
	for data: Array in enemy_weights.values():
		total_weight += data[0] as int
	if total_weight <= 0:
		return "squirrel"
	var roll := randi() % total_weight
	var cumulative := 0
	for enemy_name: String in enemy_weights:
		cumulative += enemy_weights[enemy_name][0] as int
		if roll < cumulative:
			return enemy_name
	return "squirrel"


# ── Spawning — enemies appear around player, off-screen ──────────────────

func _on_spawn_timer_timeout() -> void:
	if game_over:
		return

	# Batch size: start at 2, ramp faster
	var batch := 2
	if elapsed_time > 20.0:
		batch = 3
	if elapsed_time > 50.0:
		batch = 4
	if elapsed_time > 90.0:
		batch = 5

	for _i in range(batch):
		_spawn_one_enemy()


func _spawn_one_enemy() -> void:
	var enemy_type := _pick_enemy_type()
	var scene: PackedScene = enemy_scenes[enemy_type]
	var enemy: Node2D = scene.instantiate()
	enemy.global_position = _random_spawn_around_player()
	enemy.killed.connect(_on_enemy_killed.bind(enemy, enemy_type))
	add_child(enemy)

	# Rats sometimes bring a friend
	if enemy_type == "rat" and randf() < 0.4:
		var rat_scene: PackedScene = enemy_scenes["rat"]
		var rat2: Node2D = rat_scene.instantiate()
		rat2.global_position = _random_spawn_around_player()
		rat2.killed.connect(_on_enemy_killed.bind(rat2, "rat"))
		add_child(rat2)


# Spawn at a random point on a circle around the player
func _random_spawn_around_player() -> Vector2:
	var angle := randf() * TAU
	var offset := Vector2.from_angle(angle) * SPAWN_DISTANCE
	return player.global_position + offset


# ── Kill handling + upgrade drops ────────────────────────────────────────

func _on_enemy_killed(value: int, enemy: Node2D, enemy_type: String) -> void:
	score += value
	enemies_killed += 1
	hud.update_score(score)

	Stats.record_kill(enemy_type.capitalize(), value)
	SoundManager.play_enemy_death()

	# Drop chance — tougher enemies drop more often
	var drop_chance := UPGRADE_DROP_CHANCE
	match enemy_type:
		"mole":    drop_chance = 0.55
		"raccoon": drop_chance = 0.45
		"rat":     drop_chance = 0.20

	if randf() < drop_chance and is_instance_valid(enemy):
		_spawn_pickup(enemy.global_position)

	# 20% treasure drop independent of weapon upgrade
	if randf() < 0.20 and is_instance_valid(enemy):
		_spawn_treasure(enemy.global_position)


func _spawn_pickup(pos: Vector2) -> void:
	var pickup: Node2D = pickup_scene.instantiate()
	pickup.global_position = pos
	pickup.weapon_type = upgrade_types[randi() % upgrade_types.size()]
	pickup.collected.connect(_on_pickup_collected)
	add_child(pickup)


func _spawn_treasure(pos: Vector2) -> void:
	var t: Node2D = treasure_scene.instantiate()
	t.global_position = pos
	t.collected.connect(_on_treasure_collected)
	add_child(t)


func _on_treasure_collected() -> void:
	gold += 1
	hud.update_gold(gold)
	SoundManager.play_coin()


func _on_pickup_collected(mod_name: String) -> void:
	player.add_mod(mod_name)
	Stats.record_pickup(mod_name, player.mods[mod_name])


func _on_player_health_changed(new_health: int) -> void:
	hud.update_health(new_health)


func _on_mods_changed(mods: Dictionary) -> void:
	hud.update_mods(mods)
	_check_boss_spawn(mods)


func _on_player_died() -> void:
	game_over = true
	spawn_timer.stop()
	hud.show_game_over(score, enemies_killed)
	player.set_physics_process(false)
	SoundManager.play_player_death()
	# Play game over jingle after death sound finishes
	get_tree().create_timer(2.0).timeout.connect(func():
		SoundManager.stop_music()
		SoundManager.play_game_over()
	)


# ── Boss waves ───────────────────────────────────────────────────────────

func _check_boss_spawn(mods: Dictionary) -> void:
	if _boss_triggered or game_over:
		return
	var maxed := 0
	for level: int in mods.values():
		if level >= 3:
			maxed += 1
	if maxed >= 2:
		_boss_triggered = true
		_start_boss_wave()


func _update_boss_respawn(delta: float) -> void:
	if not _boss_triggered or _boss_wave_active or game_over:
		return
	if _boss_respawn_timer > 0.0:
		_boss_respawn_timer -= delta
		if _boss_respawn_timer <= 0.0:
			_start_boss_wave()


func _start_boss_wave() -> void:
	_boss_wave += 1
	_boss_wave_active = true
	# 1 Donald boss + N Link bosses per wave
	_bosses_alive = _boss_wave + 1
	_boss_fight_start = elapsed_time
	SoundManager.play_boss_alarm()
	# Play "running out of time" warning after alarm finishes
	get_tree().create_timer(1.5).timeout.connect(func():
		if _boss_wave_active and not game_over:
			SoundManager.play_warning()
	)
	hud.show_boss_fight()

	# Total HP: Donald (1500) + N × Link (1000)
	var total_hp: int = 1500 + _boss_wave * 1000
	hud.show_boss_hp_bar(total_hp)

	# Always spawn one Donald boss
	var donald: Node2D = donald_boss_scene.instantiate()
	donald.global_position = player.global_position + Vector2.from_angle(randf() * TAU) * SPAWN_DISTANCE
	donald.killed.connect(_on_boss_killed.bind(donald))
	donald.health_changed.connect(_on_boss_health_changed)
	add_child(donald)

	# Spawn N Link bosses
	for i in range(_boss_wave):
		var boss: Node2D = boss_scene.instantiate()
		var angle := (float(i) / float(_boss_wave)) * TAU + randf() * 0.5
		boss.global_position = player.global_position + Vector2.from_angle(angle) * SPAWN_DISTANCE
		boss.killed.connect(_on_boss_killed.bind(boss))
		boss.health_changed.connect(_on_boss_health_changed)
		add_child(boss)


func _on_boss_health_changed(_current: int, _maximum: int) -> void:
	# Sum HP across all living bosses (any enemy that emits health_changed is a boss)
	var total_hp := 0
	var total_max := 0
	for node in get_tree().get_nodes_in_group("enemies"):
		if node.has_signal("health_changed") and "MAX_HEALTH" in node and "health" in node:
			total_hp += maxi(node.health, 0)
			total_max += node.MAX_HEALTH
	hud.update_boss_hp(total_hp, total_max)


func _on_boss_killed(value: int, boss: Node2D) -> void:
	_on_enemy_killed(value, boss, "boss")
	_bosses_alive -= 1
	if _bosses_alive <= 0:
		_boss_wave_active = false
		_boss_fight_duration = elapsed_time - _boss_fight_start
		_boss_respawn_timer = _boss_fight_duration * 2.0
		hud.show_boss_defeated()
		SoundManager.play_stage_clear()
	# Boss always drops 10 treasures scattered around its death position
	if is_instance_valid(boss):
		for i in range(10):
			var angle := randf() * TAU
			var dist := randf_range(20.0, 80.0)
			_spawn_treasure(boss.global_position + Vector2.from_angle(angle) * dist)


# ── Power-ups ──────────────────────────────────────────────────────────

func _update_powerup_spawn(delta: float) -> void:
	_powerup_timer += delta
	if _powerup_timer >= POWERUP_INTERVAL:
		_powerup_timer -= POWERUP_INTERVAL
		_spawn_powerup()


func _spawn_powerup() -> void:
	var pu: Node2D = powerup_scene.instantiate()
	pu.powerup_type = powerup_types[randi() % powerup_types.size()]
	var angle := randf() * TAU
	var dist := randf_range(80.0, POWERUP_SPAWN_RADIUS)
	pu.global_position = player.global_position + Vector2.from_angle(angle) * dist
	pu.collected.connect(_on_powerup_collected)
	add_child(pu)


func _on_powerup_collected(powerup_type: String) -> void:
	match powerup_type:
		"life_pot", "nut":
			player.heal(1)
			SoundManager.play_oneup()
		"scroll_fire":
			player.apply_buff("damage", 8.0)
			SoundManager.play_powerup()
		"scroll_ice":
			_freeze_all_enemies()
			SoundManager.play_powerup()
		"scroll_thunder":
			_thunder_aoe()
			SoundManager.play_thunder()
		"gem_red":
			score += 50
			hud.update_score(score)
			SoundManager.play_coin()
		"gem_green":
			player.apply_buff("speed", 8.0)
			SoundManager.play_powerup()
		"gem_purple":
			player.apply_buff("shield", 5.0)
			SoundManager.play_powerup()
	Stats._add_event("Picked up %s" % powerup_type)
	hud.show_powerup_effect(powerup_type)


func _freeze_all_enemies() -> void:
	for enemy in get_tree().get_nodes_in_group("enemies"):
		if not is_instance_valid(enemy):
			continue
		# Freeze: stop movement and tint blue
		if enemy.has_method("set_physics_process"):
			enemy.set_physics_process(false)
		if "anim_sprite" in enemy:
			enemy.anim_sprite.modulate = Color(0.4, 0.6, 1.0, 1.0)
		# Unfreeze after duration
		get_tree().create_timer(FREEZE_DURATION).timeout.connect(
			_unfreeze_enemy.bind(enemy))


func _unfreeze_enemy(enemy: Node2D) -> void:
	if not is_instance_valid(enemy):
		return
	enemy.set_physics_process(true)
	if "anim_sprite" in enemy:
		enemy.anim_sprite.modulate = Color.WHITE


func _thunder_aoe() -> void:
	for enemy in get_tree().get_nodes_in_group("enemies"):
		if not is_instance_valid(enemy):
			continue
		var dist := player.global_position.distance_to(enemy.global_position)
		if dist <= THUNDER_RADIUS and enemy.has_method("take_damage"):
			enemy.take_damage(THUNDER_DAMAGE)
			# Yellow flash on hit
			if "anim_sprite" in enemy:
				enemy.anim_sprite.modulate = Color(1.0, 1.0, 0.3, 1.0)
				var tw := enemy.create_tween()
				tw.tween_property(enemy.anim_sprite, "modulate", Color.WHITE, 0.3)
